# Monominto Quantized Neutral
# A theme for Ghostty
# Made by Joseph Wain @ https://penandthink.com/

palette = 0=#333333
palette = 1=#cccccc
palette = 2=#686868
palette = 3=#7c7c7c
palette = 4=#868686
palette = 5=#5e5e5e
palette = 6=#b8b8b8
palette = 7=#a4a4a4
palette = 8=#a4a4a4
palette = 9=#cccccc
palette = 10=#686868
palette = 11=#7c7c7c
palette = 12=#868686
palette = 13=#5e5e5e
palette = 14=#b8b8b8
palette = 15=#868686

foreground = #cccccc
background = #121212
selection-foreground = #6bc78a
selection-background = #003a31
cursor-text = #003a31
cursor-color = #47d084
