# Monominto Quantized Warm
# A theme for Ghostty
# Made by Joseph Wain @ https://penandthink.com/

palette = 0=#38322d
palette = 1=#d2cbc5
palette = 2=#6e6761
palette = 3=#827b75
palette = 4=#8c857f
palette = 5=#635d57
palette = 6=#beb7b1
palette = 7=#aaa39d
palette = 8=#aaa39d
palette = 9=#d2cbc5
palette = 10=#6e6761
palette = 11=#827b75
palette = 12=#8c857f
palette = 13=#635d57
palette = 14=#beb7b1
palette = 15=#8c857f

foreground = #cccccc
background = #121212
selection-foreground = #6bc78a
selection-background = #003012
cursor-text = #003012
cursor-color = #228e4a
