# Monominto Light Warm
# A theme for Ghostty
# Made by Joseph Wain @ https://penandthink.com/

palette = 0=#e6e3df
palette = 1=#a4a09c
palette = 2=#94908c
palette = 3=#83807c
palette = 4=#73706c
palette = 5=#63605c
palette = 6=#53504c
palette = 7=#32302d
palette = 8=#d7d4d0
palette = 9=#83807c
palette = 10=#73706c
palette = 11=#63605c
palette = 12=#53504c
palette = 13=#43403c
palette = 14=#32302d
palette = 15=#000000

foreground = #2d291c
background = #f8f7ef
selection-foreground = #1d8c51
selection-background = #bae2cc
cursor-text = #9df194
cursor-color = #47ba74
