# Monominto Warm
# A theme for Ghostty
# Made by Joseph Wain @ https://penandthink.com/

foreground = #cccccc
background = #121212
selection-foreground = #6bc78a
selection-background = #003012
cursor-text = #003012
cursor-color = #228e4a

palette = 0=#36322f
palette = 1=#595451
palette = 2=#625d5a
palette = 3=#6a6562
palette = 4=#726d6a
palette = 5=#7b7673
palette = 6=#837e7b
palette = 7=#b4afab
palette = 8=#484340
palette = 9=#8c8784
palette = 10=#938e8b
palette = 11=#9d9895
palette = 12=#a6a19d
palette = 13=#afaaa6
palette = 14=#b9b4b0
palette = 15=#dbd5d1
