# Monominto Warm
# A theme for Ghostty
# Made by Joseph Wain @ https://penandthink.com/

background = #121212
foreground = #cdcbcc
cursor-color = #319c59
cursor-text = #003029
selection-background = #123424
selection-foreground = #69b782

palette = 0=#242428
palette = 1=#675f5f
palette = 2=#716a69
palette = 3=#7a7372
palette = 4=#837c7b
palette = 5=#8d8685
palette = 6=#968f8e
palette = 7=#cdc6c5
palette = 8=#363636
palette = 9=#a09998
palette = 10=#a8a1a0
palette = 11=#b3acab
palette = 12=#bdb6b5
palette = 13=#c8c0bf
palette = 14=#d3cccb
palette = 15=#f8f1f0
