# Monominto Neutral
# A theme for Ghostty
# Made by Joseph Wain @ https://penandthink.com/

palette = 0=#333333
palette = 1=#555555
palette = 2=#5e5e5e
palette = 3=#666666
palette = 4=#6e6e6e
palette = 5=#777777
palette = 6=#7f7f7f
palette = 7=#b0b0b0
palette = 8=#444444
palette = 9=#888888
palette = 10=#8f8f8f
palette = 11=#999999
palette = 12=#a2a2a2
palette = 13=#ababab
palette = 14=#b5b5b5
palette = 15=#d6d6d6

foreground = #cccccc
background = #121212
selection-foreground = #6bc78a
selection-background = #003a31
cursor-text = #003a31
cursor-color = #47d084
